# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 909d2dda6420a268e264a45d2e0c93a737b788d46fe5c01c156613f1ff6f3310a2997a4a5bdbf9df29e5ba8fe1b0556724863dc169c16ebec78bd248ebe1c2c2

test:
  secret_key_base: 8e1b0484594a3824f9421f476878cffcd66f6c5c3af09d87031ba7f11ed7b2c28eeb745bb457c71bf88541054a0ed7524bbba78e15547acd3b707d561a64fd19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
